# Generated by Django 3.2.12 on 2023-01-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretaria', models.CharField(max_length=100, verbose_name='Secretaria')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do serviço')),
                ('link', models.CharField(max_length=150, verbose_name='Link')),
                ('descricao', models.CharField(blank=True, max_length=150, verbose_name='Breve descrição')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destacar')),
            ],
        ),
    ]
