# Generated by Django 3.2.12 on 2023-01-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, verbose_name='Breve descrição'),
        ),
        migrations.AddField(
            model_name='servico',
            name='secretaria',
            field=models.CharField(default='', max_length=100, verbose_name='Secretaria'),
            preserve_default=False,
        ),
    ]
